name: quark-cookie

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install playwright
        run: |
          npm init -y
          npm install playwright

      - name: Get cookie
        run: |
          node <<EOF
          const { chromium } = require('playwright');
          const fs = require('fs');

          (async () => {

            const browser = await chromium.launch();
            const page = await browser.newPage();

            await page.goto("https://quark.sm.cn/s?q=桃花马上请长缨 libahao.com");

            const cookies = await page.context().cookies();

            let cookieStr = cookies.map(c=>c.name+"="+c.value).join("; ");

            fs.writeFileSync("cookie.txt", cookieStr);

            console.log(cookieStr);

            await browser.close();

          })();
          EOF
